FROM alpine:3

LABEL author="Kisah Tegar Putra Abdi"
LABEL company="KisahCode" website="https://kisahcode.web.app"

RUN mkdir hello
RUN echo "Hello World" > "hello/world.txt"

CMD cat "hello/world.txt"